project:
  type: website
  output-dir: docs

website:
  title: "Josh Goldhaber"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - text: "Data Viz"
        menu:
          - text: "Fifa Data"
            href: FifaData.qmd
          - text: "Fast Food Cals"
            href: FastFoodCals.qmd


format:
  html:
    theme: minty
    dark: solar
    css: styles.css
    toc: true
    page-layout: full
